/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataFeedApi;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Jhoel Fiorese
 * @version 0.1.0 Jaff Data Feed API
 * @serial JAFF-376021
 */
public final class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {

        initComponents();
        variavelGif.setVisible(false);
        btnClick.setEnabled(false);

        call();

    }

    public static String login;

    public static String senha;
    public static Boolean desativa = true;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void call() {

        SwingWorker worker = new SwingWorker() {
            @Override
            protected Void doInBackground() throws Exception {
                // Simulate doing something useful.
                //Faz a troca de emojis de acordo com a resposta do servidor
                setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("img/logo_jaff_circuitos.png")));
                ImageIcon icon;

                while (desativa = true) {

                    try {
                        Socket socket = new Socket("datafeedcd3.cedrotech.com", 81);
                        icon = new ImageIcon(getClass().getResource("img/check_64_pix.png"));
                        btnClick.setEnabled(true);

                        imgLabel.setIcon(icon);
                        socket.close();
                        Thread.sleep(900);
                    } catch (IOException ex) {
                        Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                        icon = new ImageIcon(getClass().getResource("img/delete_64_pix.png"));
                        btnClick.setEnabled(false);
                        variavelGif.setEnabled(false);
                        imgLabel.setIcon(icon);

                    }

                }
                return null;

            }
        };

        worker.execute();

    }

    private void verifica() {
        SwingWorker worker = new SwingWorker() {
            @Override
            protected Void doInBackground() {
                variavelGif.setVisible(true);
                txtLogin.setVisible(false);
                txtSenha.setVisible(false);
                btnClick.setVisible(false);
                // variavelGif.setIcon(icon);
                login = txtLogin.getText();
                senha = txtSenha.getText();

                try {

                    Ativo a = new Ativo();

                    String b = a.login(login, senha);

                    a.in.close();
                    a.dOut.close();

                    if (b.equals("1")) {
                        //JOptionPane.showMessageDialog(rootPane, "Bem vindo! " + login);

                        a.client.close();

                        TelaPrincipal frame = new TelaPrincipal();
                        frame.setVisible(true);

                        dispose();

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Senha ou login incorreto! ");
                        variavelGif.setVisible(false);
                        txtLogin.setVisible(true);
                        txtSenha.setVisible(true);
                        btnClick.setVisible(true);

                    }

                } catch (IOException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);

                }
                return null;
            }
        };

        worker.execute();

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        variavelGif = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        btnClick = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(610, 358));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        variavelGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataFeedApi/img/loading1.gif"))); // NOI18N
        getContentPane().add(variavelGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 430, 220));

        jLabel2.setFont(new java.awt.Font("Corbel", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("JAFF");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 12, 20));
        jLabel3.setText("Senha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
        });
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 160, 30));

        txtSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 160, 30));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 247, 49));
        jLabel5.setText("Login");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));
        getContentPane().add(imgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 70, 70));

        btnClick.setBackground(new java.awt.Color(0, 255, 102));
        btnClick.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnClick.setText("Entrar");
        btnClick.setAutoscrolls(true);
        btnClick.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });
        btnClick.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnClickKeyPressed(evt);
            }
        });
        getContentPane().add(btnClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        // TODO add your handling code here:
        verifica();

    }//GEN-LAST:event_btnClickActionPerformed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            verifica();
    }//GEN-LAST:event_txtSenhaKeyPressed
    }
    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            verifica();

        }
    }//GEN-LAST:event_txtLoginKeyPressed

    private void btnClickKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnClickKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            verifica();
        }
    }//GEN-LAST:event_btnClickKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClick;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JLabel variavelGif;
    // End of variables declaration//GEN-END:variables
}
